name: Main build
run-name: Main build by ${{ github.actor }} ðŸš€
on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'ðŸš€ Test & Deploy'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/goldstack-setup
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.10.2'
      - run: |
          yarn build
          yarn test
          yarn infra up prod
          yarn deploy prod
    env:
      CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
      CONTACT_EMAIL_SHALLY: ${{ secrets.CONTACT_EMAIL_SHALLY }}
      RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}

  screenshots:
    name: 'ðŸ“¸ Take Screenshots'
    runs-on: ubuntu-latest
    needs: build
    env:
      URLS: |
        https://pureleap.com
        https://pureleap.com/gifts/commonplace-ecosystem
        https://pureleap.com/gifts/river-not-a-bucket
        https://pureleap.com/gifts/commonplace-book
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/goldstack-setup
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Take screenshots
        run: |
          cd packages/ui
          yarn playwright install --with-deps
          yarn node scripts/screenshot.js
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: packages/ui/screenshots/
